package com.yasinyazici.riot.request.web;

import com.yasinyazici.riot.config.Config;
import com.yasinyazici.riot.data.exceptions.WrongRequestFormatException;
import com.yasinyazici.riot.request.types.RequestType;
import com.yasinyazici.riot.request.web.RequestCreator;
import com.yasinyazici.riot.request.web.RequestFormat;
import com.yasinyazici.riot.request.web.RequestProperty;

import java.net.MalformedURLException;
import java.util.Arrays;
import java.util.stream.Stream;

/**
 * <p>Used for modifying the link lodged in the {@link RequestType} instance in the {@link RequestProperty} class so it can be used as a valid url to make a request and return data.</p>
 *
 * @author Yasin
 */
public class RequestLink {

    private RequestProperty requestProperty;


    /**
     * <p>Creates a new {@link RequestLink} instance</p>
     *
     * @param requestProperty the request property to assign the request to
     */
    public RequestLink(RequestProperty requestProperty) {
        this.requestProperty = requestProperty;
    }

    /**
     * <p>Puts together the link so it's ready to get modified by the method {@link #getModifiedLink()}</p>
     *
     * @return the merged link so it can be modified by {@link #getModifiedLink()}
     */
    private String generateLink() {
        RequestType requestType = requestProperty.getRequestType();
        return requestType.getStart() + requestType.getLink() + "?api_key=" + Config.API_KEY.getApiKey() + "&" + requestType.getQueryParameter();
    }

    /**
     * <p>Modifies the link generated by method {@link #generateLink()} and replaces the parameters given with the parameters identified (placeholders) in the corresponding order.</p>
     *
     * @return a modified version of {@link #generateLink()} to be used in the {@link Request#makeRequest()} procedure
     * @throws WrongRequestFormatException thrown when the parameters given do not equal the amount of parameters (placeholders) identified
     */
    public String getModifiedLink() throws WrongRequestFormatException {
        String modifiedLink = generateLink();
        String[] neededVariables = new RequestFormat(modifiedLink).getVariables(); // The variables needed
        Object[] givenVariables = requestProperty.getParameters();
        int variablesLength = neededVariables.length;
        if (givenVariables.length != variablesLength) {
            throw new WrongRequestFormatException("The amount of parameters do not equal the amount needed.", neededVariables);
        }
        for (int i = 0; i < variablesLength; i++) {
            String neededVariable = neededVariables[i];
            Object givenVariable = givenVariables[i];
            modifiedLink = modifiedLink.replace(neededVariable, givenVariable instanceof String[] ? String.join(",", Arrays.asList((String[]) givenVariable)) : String.valueOf(givenVariables[i])).replace(" ", "");
        }
        return modifiedLink;
    }

}
